version: '3.8'

services:
  diun2homer:
    image: ghcr.io/${GITHUB_REPOSITORY:Rjvs/diun2homer}:latest
    ports:
      - "8000:8000"
    volumes:
      - diun2homer-data:/app/data
    environment:
      - DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  diun2homer-data:
